version: '3'

services:
  psql:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=berni
      - POSTGRES_PASSWORD=Karmapa108
    volumes:
      - psql:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: 'jspringio/timebuyers'
    ports:
      - '8080:8080'
    build:
      context: .
    container_name: timebuyers
    depends_on:
      - psql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql:5432/berni
      - SPRING_DATASOURCE_USERNAME=berni
      - SPRING_DATASOURCE_PASSWORD=Karmapa108
    links:
      - psql
    volumes:
      - './:/src'
volumes:
  psql:
    driver: local
