name: CI-CD

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
      build_test:
        name: Build & Test App
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [ 14.x ]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - uses: actions/checkout@v2

          - name: setup node
            uses: actions/setup-node@master
            with:
              node-version: ${{ matrix.node-version }}

          # install application dependencies
          - name: Install dependencies
            run: |
              npm install
              npm ci

          - name: build & test
            working-directory: ./src/frontend/timebuyers_app
            run: |
              npm run lint
              npm run build
# copy static built files locally from frontend to backend
              cp ./build/* ../../backend/main/resources/static


